name: churchapp
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  graphql_flutter: ^3.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  carousel_slider: ^2.0.0
  google_fonts: ^0.3.10
  google_sign_in: ^4.4.1
  http: ^0.12.0+4
  youtube_player_flutter: ^6.1.0+4
  provider: ^4.0.5
  flutter_dotenv: ^2.1.0
  shared_preferences: ^0.5.7
  cached_network_image: ^2.2.0
  flutter_staggered_grid_view: ^0.3.0
  stripe_payment: ^1.0.7
  stripe_sdk: ^2.8.1
  awesome_card: ^1.1.0
  mask_text_input_formatter: ^1.0.6
  flutter_svg: ^0.17.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/berit-1.png
    - images/berit-2.png
    - images/playlistimage.jpg
    - images/kimjungoh.png
    - images/epc-main.png
    - images/main-bg.png
    - images/main-bg-1.png
    - images/dot.png
    - images/cross.png
    - images/icons/arrow-left.svg
    - images/icons/cross.svg
    - images/icons/church.svg
    - images/icons/employee.svg
    - images/icons/service-info.svg
    - images/icons/contact.svg
    - images/icons/news.svg
    - google_fonts/
    - .env
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
